require("harpoon").setup()

local harpoon_term = require("harpoon.term")
vim.keymap.set("n", "<Leader>t1", function()
  harpoon_term.gotoTerminal(1)
end)
vim.keymap.set("n", "<Leader>t2", function()
  harpoon_term.gotoTerminal(2)
end)
vim.keymap.set("n", "<Leader>t3", function()
  harpoon_term.gotoTerminal(3)
end)
vim.keymap.set("n", "<Leader>t4", function()
  harpoon_term.gotoTerminal(4)
end)
