tap "gdubw/gng"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

brew "bat"
brew "coreutils"
brew "curl"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "glow"
brew "gng"
brew "go"
brew "graphviz"
brew "htop"
brew "jq"
brew "languagetool"
brew "luajit", args: ["HEAD"]
brew "luarocks"
brew "luv"
brew "neovim", args: ["HEAD"]
brew "node"
brew "nvim"
brew "nvm"
brew "proselint"
brew "ripgrep"
brew "starship"
brew "stylua"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "whalebrew"
brew "yq"
brew "zsh"

cask "amethyst"
cask "docker"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "iterm2"
cask "jetbrains-toolbox"
cask "visual-studio-code"

whalebrew "whalebrew/neuron"
