tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

cask "docker"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "jetbrains-toolbox"
cask "ghostty"
cask "spotify"
cask "visual-studio-code"

vscode "asvetliakov.vscode-neovim"
vscode "editorconfig.editorconfig"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "k--kato.intellij-idea-keybindings"
vscode "linhmtran168.mac-ca-vscode"
