[directory]
style = "bold blue"

[cmd_duration]
style = "bold green"

[git_state]
style = "bold green"

[git_status]
disabled = true

[username]
style_user = "bold blue"

[hostname]
style = "bold green"
